[package]
name = "luro"
version = "0.0.1"
authors = ["Nurah Wolfo <nurah@wolfo.tech>"]
edition = "2018"
description = "A furry discord bot"
readme = "README.md"
repository = "https://github.com/nurahwolf/luro-rs"
license = "MIT"
keywords = ["async", "twilight", "discord", "slash-command"]
categories = ["asynchronous"]

[dependencies]
async-trait = "0.1"
parking_lot = "0.12"
tracing = "0.1"
twilight-model = "0.15"
twilight-http = "0.15"
twilight-gateway = "0.15"
twilight-util = { version = "0.15", features = ["builder", "permission-calculator", "snowflake"] }
futures-util = "0.3.28"
anyhow = "1.0.71"
tracing-subscriber = "0.3.17"
twilight-lavalink = "0.15.1"
hyper = "0.14.27"
twilight-interactions = "0.15.2"
twilight-cache-inmemory = "0.15.2"
serde_json = "1.0.102"
serde = "1.0.171"
toml = "0.7.6"
rand = "0.8.5"
git2 = "0.17.2"
memory-stats = "1.1.0"
# luro-framework = { path = "../luro-framework", version = "0" }

[dependencies.tokio]
version = "1"
default-features = false
features = ["sync"]

[dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
