[package]
name = "luro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core
tokio = { features = ["macros", "rt-multi-thread", "fs"], version = "1" } # Our multithreaded runner
anyhow = { version = "1.0", features = ["backtrace"] } # For errors
futures = { default-features = false, version = "0.3"} 
tracing = "0.1" # More helpful error messages
tracing-subscriber = "0.3" # For the twilight runtime

# For features
hyper = { features = ["client", "server", "http2", "runtime"], version = "0.14" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
memory-stats = "1"
git2 = "0.16"
toml = "0.7"
rand = "0.8"

# Twilight specific
twilight-cache-inmemory = "0.15"
twilight-gateway = "0.15"
twilight-http = "0.15"
twilight-model = "0.15"
twilight-interactions = "0.15"
twilight-standby = "0.15"
twilight-lavalink = "0.15"
twilight-util = {version = "0.15", features = ["builder"]}