[workspace]
members = [
    "luro",
    "luro-model",
    "twilight-interactions",
    "twilight-interactions-derive"
]
resolver = "2"

[workspace.package]
authors = ["Nurah Wolfo <nurah@wolfo.tech>"]
categories = ["asynchronous"]
description = "A furry discord bot"
edition = "2021"
keywords = ["async", "twilight", "discord", "slash-command"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nurahwolf/luro-rs"
version = "0.0.1"

[workspace.dependencies]
# Twilight
twilight-model = { git = "https://github.com/twilight-rs/twilight.git", branch = "next" }

# Twilight third party
twilight-interactions = { path = "twilight-interactions" }