[workspace]
members = [
    "luro",
    "luro-database",
    "luro-model",
    "twilight-interactions",
    "twilight-interactions-derive"
]
resolver = "2"

[workspace.package]
authors = ["Nurah Wolfo <nurah@wolfo.tech>"]
categories = ["asynchronous"]
description = "A furry discord bot"
edition = "2021"
keywords = ["async", "twilight", "discord", "slash-command"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nurahwolf/luro-rs"
version = "0.0.1"

[workspace.dependencies]
# Twilight
twilight-model = { git = "https://github.com/twilight-rs/twilight.git", branch = "next" }

# Twilight third party
twilight-interactions = { path = "twilight-interactions" }

# Core
anyhow = "1"
serde = "1"
dashmap = "5"
tokio = { version = "1", default-features = false, features = ["sync", "rt-multi-thread", "fs"] }
# TODO: MOVE TO DATABASE
toml = "0.7"
tracing = "0.1"

[workspace.dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }