[package]
name = "luro"
version = "0.1.0"
authors = ["Nurah Wolfo <nurah@wolfo.tech>"]
edition = "2021"


[dependencies]
tracing = "0.1" # Useful for logs and I should use it some more. It's required by a bunch of dependencies, so might as well make use of it.
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = { version = "0.3.28", default-features = false } # For Discord autocomplete
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }

# Luro Components
# luro_sled = { path = "lib/luro_sled" }
# luro_songbird = { path = "lib/luro_songbird" }
# luro_utilities = { path = "lib/luro_utilities" }
luro_core = { path = "lib/luro_core" }
# luro_e621 = { path = "lib/luro_e621" }
# luro_furaffinity = { path = "lib/luro_furaffinity" }
luro_events = { path = "lib/luro_events" }
luro_commands = { path = "lib/luro_commands" }

### Dependencies that have a real reason to exist
[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "signal"]

[dependencies.serenity]
default-features = false
features = ["rustls_backend", "voice", "unstable_discord_api", "model"]
version = "0.11"

[dependencies.poise]
features = ["cache"]
version = "0.5"

[dependencies.songbird]
features = ["builtin-queue"]
version = "0.3"

[workspace]
members = ["lib/*"]