INSERT INTO messages (
        activity,
        application_id,
        application,
        attachments,
        author,
        channel_id,
        components,
        content,
        deleted,
        edited_timestamp,
        embeds,
        flags,
        guild_id,
        message_id,
        interaction,
        kind,
        mention_channels,
        mention_everyone,
        mention_roles,
        mentions,
        pinned,
        reactions,
        reference,
        referenced_message,
        role_subscription_data,
        source,
        sticker_items,
        thread,
        timestamp,
        tts,
        webhook_id,
        member,
        author_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        false,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32
    ) ON CONFLICT (message_id) DO
UPDATE
SET activity = $1,
    application_id = $2,
    application = $3,
    attachments = $4,
    author_id = $32,
    author = $5,
    channel_id = $6,
    components = $7,
    content = $8,
    deleted = false,
    edited_timestamp = $9,
    embeds = $10,
    flags = $11,
    guild_id = $12,
    interaction = $14,
    kind = $15,
    mention_channels = $16,
    mention_everyone = $17,
    mention_roles = $18,
    mentions = $19,
    pinned = $20,
    reactions = $21,
    reference = $22,
    referenced_message = $23,
    role_subscription_data = $24,
    source = $25,
    sticker_items = $26,
    thread = $27,
    timestamp = $28,
    tts = $29,
    webhook_id = $30,
    member = $31