[package]
name = "luro-framework"
version = "0.0.1"
authors = ["Nurah Wolfo <nurah@wolfo.tech>"]
edition = "2018"
description = "A furry discord bot"
readme = "README.md"
repository = "https://github.com/nurahwolf/luro-rs"
license = "MIT"
keywords = ["async", "twilight", "discord", "slash-command"]
categories = ["asynchronous"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
luro-macros = { path = "../luro-macros", version = "0" }
parking_lot = "0.12"
tracing = "0.1"
twilight-model = "0.15"
twilight-http = "0.15"

[dependencies.tokio]
version = "1"
default-features = false
features = ["sync"]

[features]
rc = []

[dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
