CREATE TABLE IF NOT EXISTS channels (
    channel_id bigint NOT NULL,
    guild_id bigint,
    deleted boolean DEFAULT false NOT NULL,
    application_id bigint,
    bitrate integer,
    default_auto_archive_duration smallint,
    default_forum_layout smallint,
    default_reaction_emoji jsonb,
    default_sort_order smallint,
    default_thread_rate_limit_per_user smallint,
    flags bigint,
    icon text,
    invitable boolean,
    video_quality_mode smallint,
    user_limit integer,
    topic text,
    kind smallint DEFAULT 69 NOT NULL,
    last_message_id bigint,
    last_pin_timestamp timestamp with time zone,
    managed boolean,
    member jsonb,
    member_count smallint,
    message_count integer,
    name text,
    column_name integer,
    nsfw boolean,
    owner_id bigint,
    parent_id bigint,
    permission_overwrites jsonb[],
    "position" integer,
    rate_limit_per_user smallint,
    recipients bigint[],
    rtc_region text,
    thread_metadata jsonb,
    newly_created boolean,
    applied_tags bigint[],
    available_tags jsonb[]
);