CREATE VIEW public.guild_member_user AS
SELECT
    NULL::integer AS accent_colour,
    NULL::text AS avatar,
    NULL::text AS avatar_decoration,
    NULL::bigint AS averagesize,
    NULL::text AS banner,
    NULL::boolean AS bot,
    NULL::integer[] AS characters,
    NULL::smallint AS discriminator,
    NULL::text AS email,
    NULL::bigint AS user_flags,
    NULL::text AS global_name,
    NULL::text AS locale,
    NULL::bigint AS message_edits,
    NULL::bigint[] AS messages,
    NULL::boolean AS mfa_enabled,
    NULL::jsonb AS moderation_actions,
    NULL::bigint AS moderation_actions_performed,
    NULL::text AS name,
    NULL::smallint AS premium_type,
    NULL::bigint AS public_flags,
    NULL::boolean AS system,
    NULL::bigint AS user_id,
    NULL::boolean AS verified,
    NULL::bigint[] AS warnings,
    NULL::bigint AS words_average,
    NULL::bigint AS words_count,
    NULL::public.user_permissions AS user_permissions,
    NULL::text AS guild_avatar,
    NULL::timestamp with time zone AS boosting_since,
    NULL::timestamp with time zone AS communication_disabled_until,
    NULL::boolean AS deafened,
    NULL::bigint AS guild_id,
    NULL::timestamp with time zone AS joined_at,
    NULL::bigint AS member_flags,
    NULL::boolean AS muted,
    NULL::text AS nickname,
    NULL::boolean AS pending,
    NULL::bigint[] AS roles;