INSERT INTO guilds (
        afk_channel_id,
        afk_timeout,
        application_id,
        banner,
        default_message_notifications,
        discovery_splash,
        explicit_content_filter,
        guild_id,
        icon,
        max_members,
        max_presences,
        mfa_level,
        name,
        nsfw_level,
        owner,
        owner_id,
        permissions,
        preferred_locale,
        premium_progress_bar_enabled,
        premium_subscription_count,
        premium_tier,
        public_updates_channel_id,
        rules_channel_id,
        splash,
        system_channel_flags,
        system_channel_id,
        vanity_url_code,
        verification_level,
        widget_channel_id,
        widget_enabled
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30
    ) ON CONFLICT (guild_id) DO
UPDATE
SET afk_channel_id = $1,
    afk_timeout = $2,
    application_id = $3,
    banner = $4,
    default_message_notifications = $5,
    discovery_splash = $6,
    explicit_content_filter = $7,
    icon = $9,
    max_members = $10,
    max_presences = $11,
    mfa_level = $12,
    name = $13,
    nsfw_level = $14,
    owner = $15,
    owner_id = $16,
    permissions = $17,
    preferred_locale = $18,
    premium_progress_bar_enabled = $19,
    premium_subscription_count = $20,
    premium_tier = $21,
    public_updates_channel_id = $22,
    rules_channel_id = $23,
    splash = $24,
    system_channel_flags = $25,
    system_channel_id = $26,
    vanity_url_code = $27,
    verification_level = $28,
    widget_channel_id = $29,
    widget_enabled = $30