[package]
name = "luro-database"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
toml = { version = "0.8", optional = true }
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres" ], optional = true }
luro-model.path = "../luro-model"
twilight-model = { workspace = true }
futures-util = "0.3"   # main

# Default Features
[features]
default = ["sqlx-driver"]

## Database Options
toml-driver = ["dep:toml"]
sqlx-driver = ["dep:sqlx"]