[package]
name = "luro-database"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
anyhow = { workspace = true }
bincode = { version = "1", optional = true }
futures-util = "0.3" # main
luro-model.path = "../luro-model"
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "postgres",
    "json",
    "time",
], optional = true }
toml = { version = "0.8", optional = true }
twilight-model = { workspace = true }
time = { version = "0.3", optional = true }
tracing = { workspace = true }
twilight-cache-inmemory = { workspace = true, optional = true } #framework


# Default Features
[features]
default = ["sqlx-driver", "cache"]

## Database Options
toml-driver = ["dep:toml"]
sqlx-driver = ["dep:sqlx", "dep:bincode", "time"]

## Misc Features
cache = ["dep:twilight-cache-inmemory"] # Only used for allowing cached items be converted to database items. If not needed, disable this feature
