[package]
name = "luro-model"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
# Luro Specific
# luro-builder = { path = "../luro-builder" }

# For feature dice-roller
rand = { workspace = true, optional = true}

anyhow = { workspace = true }
dashmap = { workspace = true, features = ["serde"]}
serde = { workspace = true }
twilight-cache-inmemory = { workspace = true }
twilight-http = { workspace = true }
twilight-lavalink = { workspace = true }
twilight-model = { workspace = true }
tracing-subscriber = { workspace = true }
twilight-interactions = { workspace = true }
hyper = { workspace = true }
twilight-gateway = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
twilight-util = { workspace = true }

[features]
default = ["toml-driver", "dice-roller"]
toml-driver = []
dice-roller = ["dep:rand"]
