[package]
name = "luro-model"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix_trie = { version = "0.2", optional = true } # command
nom = { version = "7", optional = true } # command/text_args
luro-builder.path = "../luro-builder" # interaction
rand = { workspace = true, optional = true} # feature dice-roller

anyhow = { workspace = true }
serde = { workspace = true }
twilight-cache-inmemory = { workspace = true }
twilight-http = { workspace = true }
twilight-lavalink = { workspace = true }
twilight-model = { workspace = true }
tracing-subscriber = { workspace = true }
twilight-interactions.path = "../twilight-interactions"
hyper = { workspace = true }
twilight-gateway = { workspace = true }
tracing = { workspace = true }
twilight-util = { workspace = true }

[features]
default = ["toml-driver", "dice-roller", "luro-command", "lavalink", "auto-trim"]
toml-driver = []
dice-roller = ["dep:rand"]
luro-command = ["dep:radix_trie", "dep:nom"]
lavalink = [] # Enable this feature to have Luro respond to lavalink events
auto-trim = [] # Used to automatically trim message responses that are too big, sending as a file instead