--! user_update_twilight_user (avatar_decoration?, email?, global_name?, verified?, user_system?, premium_type?, mfa_enabled?, locale?, user_avatar?, user_banner?, accent_colour?)
INSERT INTO users (
        accent_colour,
        avatar_decoration,
        bot,
        discriminator,
        email,
        global_name,
        locale,
        mfa_enabled,
        premium_type,
        user_avatar,
        user_banner,
        user_id,
        user_name,
        user_system,
        verified
    )
VALUES (
        :accent_colour,
        :avatar_decoration,
        :bot,
        :discriminator,
        :email,
        :global_name,
        :locale,
        :mfa_enabled,
        :premium_type,
        :user_avatar,
        :user_banner,
        :user_id,
        :user_name,
        :user_system,
        :verified
    ) ON CONFLICT (user_id) DO
UPDATE
SET accent_colour = :accent_colour,
    avatar_decoration = :avatar_decoration,
    bot = :bot,
    discriminator = :discriminator,
    email = :email,
    global_name = :global_name,
    locale = :locale,
    mfa_enabled = :mfa_enabled,
    premium_type = :premium_type,
    user_avatar = :user_avatar,
    user_banner = :user_banner,
    user_name = :user_name,
    user_system = :user_system,
    verified = :verified;