INSERT INTO guilds (
        afk_channel_id,
        afk_timeout,
        application_id,
        approximate_presence_count,
        banner,
        default_message_notifications,
        discovery_splash,
        explicit_content_filter,
        guild_id,
        icon,
        joined_at,
        large,
        max_members,
        max_presences,
        max_video_channel_users,
        mfa_level,
        name,
        nsfw_level,
        owner,
        owner_id,
        permissions,
        preferred_locale,
        premium_progress_bar_enabled,
        premium_subscription_count,
        premium_tier,
        public_updates_channel_id,
        rules_channel_id,
        safety_alerts_channel_id,
        splash,
        system_channel_flags,
        system_channel_id,
        unavailable,
        vanity_url_code,
        verification_level,
        widget_channel_id,
        widget_enabled
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36
    ) ON CONFLICT (guild_id) DO
UPDATE SET 
        afk_channel_id = $1,
        afk_timeout = $2,
        application_id = $3,
        approximate_presence_count = $4,
        banner = $5,
        default_message_notifications = $6,
        discovery_splash = $7,
        explicit_content_filter = $8,
        icon = $10,
        joined_at = $11,
        large = $12,
        max_members = $13,
        max_presences = $14,
        max_video_channel_users = $15,
        mfa_level = $16,
        name = $17,
        nsfw_level = $18,
        owner = $19,
        owner_id = $20,
        permissions = $21,
        preferred_locale = $22,
        premium_progress_bar_enabled = $23,
        premium_subscription_count = $24,
        premium_tier = $25,
        public_updates_channel_id = $26,
        rules_channel_id = $27,
        safety_alerts_channel_id = $28,
        splash = $29,
        system_channel_flags = $30,
        system_channel_id = $31,
        unavailable = $32,
        vanity_url_code = $33,
        verification_level = $34,
        widget_channel_id = $35,
        widget_enabled = $36