INSERT INTO messages (
        activity,
        application_id,
        application,
        attachments,
        author,
        author_id,
        channel_id,
        components,
        content,
        deleted,
        edited_timestamp,
        embeds,
        flags,
        guild_id,
        message_id,
        interaction,
        kind,
        mention_channels,
        mention_everyone,
        mention_roles,
        mentions,
        pinned,
        reactions,
        reference,
        referenced_message,
        role_subscription_data,
        source,
        sticker_items,
        thread,
        timestamp,
        tts,
        webhook_id,
        member
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33
    ) ON CONFLICT (message_id) DO
UPDATE
SET activity = $1,
    application_id = $2,
    application = $3,
    attachments = $4,
    author = $5,
    author_id = $6,
    channel_id = $7,
    components = $8,
    content = $9,
    deleted = $10,
    edited_timestamp = $11,
    embeds = $12,
    flags = $13,
    guild_id = $14,
    interaction = $16,
    kind = $17,
    mention_channels = $18,
    mention_everyone = $19,
    mention_roles = $20,
    mentions = $21,
    pinned = $22,
    reactions = $23,
    reference = $24,
    referenced_message = $25,
    role_subscription_data = $26,
    source = $27,
    sticker_items = $28,
    thread = $29,
    timestamp = $30,
    tts = $31,
    webhook_id = $32,
    member = $33