[package]
name = "luro-twilight"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core
anyhow = { workspace = true } # authored, interaction

# Twilight
twilight-model = { workspace = true } # authored, interaction, command, emote, command/command_kind
twilight-interactions = { workspace = true } # command

# Misc
radix_trie = "0.2" # command
nom = "7" # command/text_args
