[package]
name = "luro-twilight"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core
dotenv = "0.15" # main
anyhow = { workspace = true } # main

# Commands
luro-dice = { path = "../luro-dice", optional = true}

# Tokio
tokio.workspace = true # main
futures-util = "0.3" # main

# Luro - Specify the driver using the feature setting below
luro-database = { path = "../luro-database", features = ['toml-driver']} # main
luro-model.path = "../luro-model" # main
luro-framework.path = "../luro-framework" 


# Tracing
tracing = { workspace = true } # main
tracing-appender = "0.2" # main
tracing-subscriber = { workspace = true } # main

# Twilight
twilight-model = { workspace = true } # event_listener
twilight-gateway.workspace = true # main
twilight-interactions.path = "../twilight-interactions" # commands

[features]
# Main Features
default = ["commands"]
commands = ["command-say", "command-dice"]

# Commands
command-say = []
command-dice = ["dep:luro-dice"]